// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewVocab struct {
	LearningLang     string `json:"learning_lang"`
	FirstLang        string `json:"first_lang"`
	Alternatives     string `json:"alternatives"`
	Skill            string `json:"skill"`
	Infinitive       string `json:"infinitive"`
	Pos              string `json:"pos"`
	Hint             string `json:"hint"`
	NumLearningWords int    `json:"num_learning_words"`
	KnownLangCode    string `json:"known_lang_code"`
	LearningLangCode string `json:"learning_lang_code"`
}

type Query struct {
}

type UpdateVocab struct {
	ID               string `json:"id"`
	FirstLang        string `json:"first_lang"`
	Alternatives     string `json:"alternatives"`
	Skill            string `json:"skill"`
	Infinitive       string `json:"infinitive"`
	Pos              string `json:"pos"`
	Hint             string `json:"hint"`
	NumLearningWords int    `json:"num_learning_words"`
	KnownLangCode    string `json:"known_lang_code"`
	LearningLangCode string `json:"learning_lang_code"`
}

type Vocab struct {
	ID               string `json:"id"`
	LearningLang     string `json:"learning_lang"`
	FirstLang        string `json:"first_lang"`
	Alternatives     string `json:"alternatives"`
	Skill            string `json:"skill"`
	Infinitive       string `json:"infinitive"`
	Pos              string `json:"pos"`
	Hint             string `json:"hint"`
	NumLearningWords int    `json:"num_learning_words"`
	KnownLangCode    string `json:"known_lang_code"`
	LearningLangCode string `json:"learning_lang_code"`
}
